# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answers', django_mysql.models.JSONField(default=dict)),
                ('question', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=b'question_images')),
                ('category', models.CharField(choices=[(b'L', b'Location'), (b'T', b'Trivia'), (b'H', b'History'), (b'P', b'People')], default=b'T', max_length=1)),
                ('learn_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('score', django_mysql.models.JSONField(default=b'{"T": 0, "L": 0, "P": 0, "H": 0, "B": 0}')),
                ('number_of_questions', django_mysql.models.JSONField(default=b'{"T": 0, "L": 0, "P": 0, "H": 0}')),
                ('total_score', models.IntegerField(default=0)),
                ('quizes_played', models.IntegerField(default=0)),
                ('location', models.CharField(choices=[(b'C', b'City Centre'), (b'W', b'West'), (b'N', b'North'), (b'E', b'East'), (b'S', b'South')], default=b'C', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
