# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hciproject', '0002_auto_20161122_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='learn_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[(b'C', b'City Centre'), (b'W', b'West'), (b'N', b'North'), (b'E', b'East'), (b'S', b'South')], default=b'C', max_length=1),
        ),
    ]
