# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hciproject', '0004_auto_20161123_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
