# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hciproject', '0005_userprofile_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quizes_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=django_mysql.models.JSONField(default=b'{"T": 0, "L": 0, "P": 0, "H": 0, "B": 0}'),
        ),
    ]
