# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 01:19
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hciproject', '0006_auto_20161128_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_questions',
            field=django_mysql.models.JSONField(default=b'{"T": 0, "L": 0, "P": 0, "H": 0}'),
        ),
    ]
